name: Code Tests

on: [push, pull_request]

jobs:
    tests:
        strategy:
            matrix:
                php: ['8.0', '8.1', '8.2', '8.3', '8.4']
                symfony: [ '' ] # Don't lock to a specific symfony version by default
                include:
                    # Test lowest dependencies
                    -   deps: 'lowest'
                        php: '8.0'

                    # Test latest php with LTS versions.
                    -   deps: 'lts'
                        php: '8.4'
                        symfony: '^5.4'

                    # Test latest php with LTS versions.
                    -   deps: 'lts'
                        php: '8.4'
                        symfony: '^6.4'

        name: 'Test ${{ matrix.deps }} | PHP ${{ matrix.php }} | Symfony ${{ matrix.symfony }}'
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

            -   name: Set-up env variables
                run: |
                    case "${{ matrix.deps }}" in
                     "lowest")
                       echo "COMPOSER_FLAGS=--prefer-lowest" >> $GITHUB_ENV
                       echo "SYMFONY_REQUIRE=$(echo '${{ matrix.symfony }}')" >> $GITHUB_ENV
                       ;;
                     *)
                       echo "SYMFONY_REQUIRE=$(echo '${{ matrix.symfony }}')" >> $GITHUB_ENV
                    esac


            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: pdo_sqlite, pdo_mysql, pdo_pgsql
                    tools: flex
                    coverage: none

            -   name: Install Composer Dependencies
                run: composer update --prefer-dist --no-progress $COMPOSER_FLAGS

            -   name: Run phpunit
                run: vendor/bin/phpunit
